version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    container_name: lacco-backend
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - lacco-network

  frontend:
    build:
      context: ./Frontend
    container_name: lacco-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - lacco-network

networks:
  lacco-network:
    driver: bridge