version: "3.9"

services:
  backend:
    image: matysz21/lacco-backend:latest
    container_name: lacco-backend
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - monitoring-network

  frontend:
    image: matysz21/lacco-frontend:latest
    container_name: lacco-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - monitoring-network

networks:
  monitoring-network:
    external: true
    name: monitoring