apiVersion: v1
kind: Service
metadata:
  name: backend  # Ta nazwa jest kluczowa!
spec:
  selector:
    app: lacco-backend
  ports:
    - protocol: TCP
      port: 8080      # Port, na którym słucha serwis
      targetPort: 8080 # Port wewnątrz kontenera
