name: Deploy Lacco

on:
  push:
    branches: ["master"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Budowanie obrazu Backend
      - name: Build Docker image
        run: docker build -t lacco-app -f Backend/Dockerfile Backend

      # 2. Logowanie do DockerHub
      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Tagowanie i wysyłka obrazu
      - name: Push image to DockerHub
        run: |
          docker tag lacco-app ${{ secrets.DOCKER_USERNAME }}/lacco-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lacco-app:latest

      # 4. Deploy na serwerze przez SSH
      - name: Deploy on server (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Pobranie najnowszego obrazu
            docker pull ${{ secrets.DOCKER_USERNAME }}/lacco-app:latest

            # 2. Zatrzymanie i usunięcie starego kontenera
            # Używamy lacco-backend, aby pasowało do konfiguracji Prometheusa
            docker stop lacco-backend || true
            docker rm lacco-backend || true

            # 3. Uruchomienie nowego kontenera
            # --network monitoring: łączy aplikację z Prometheusem i Grafaną
            # --name lacco-backend: nazwa, której szuka Prometheus
            docker run -d \
              --restart unless-stopped \
              --network monitoring \
              -p 8081:8081 \
              --name lacco-backend \
              -e SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}" \
              -e SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}" \
              -e MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" \
              -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
              ${{ secrets.DOCKER_USERNAME }}/lacco-app:latest

            # 4. Czyszczenie starych obrazów (oszczędność miejsca na dysku)
            docker image prune -f